### ISSUE TITLE
Notices due to late eligibility check

### ISSUE THREAD

**Issue by unixtam** [shazahm1/Easy-Table-of-Contents#25] opened 2018-03-16 15:13 UTC
When using eztoc together with code that applies `the_content` filters to posts outside the main query (e.g. search results of the relevanssi search plugin), the following notices are triggered:

```
Notice: Trying to get property of non-object in /wp-content/plugins/easy-table-of-contents/easy-table-of-contents.php on line 599

Notice: Trying to get property of non-object in /wp-content/plugins/easy-table-of-contents/easy-table-of-contents.php on line 600

Notice: Trying to get property of non-object in /wp-content/plugins/easy-table-of-contents/easy-table-of-contents.php on line 601
```

**Comment by shazahm1** [comment] 2018-03-16 17:57
What level of testing have you done to ensure no regressions? The couple items that concern me is the shortcode and the front page (with it enabled/disabled).

I like moving the TOC eligibility check up. I think this might also fix similar errors other have reporting when using Yoast SEO. Something I have not been able to duplicate on my sites.

**Comment by unixtam** [comment] 2018-03-16 18:11
I have now tested #26 with respect to the shortcode and homepage display. Let me put it this way: They work the same way as before.

There is something off with the shortcode display. Inserting "[toc]" somewhere in a page will not show the TOC at that position. A TOC will only be shown when I check "Insert table of contents." in the ezTOC post edit meta box. So there seems to be something wrong there, but it's not due to the changes I have made.

**Comment by shazahm1** [comment] 2018-03-16 18:58
Ok, Thanks! I'll try to pull this down next week and give it a test too.

In regards to the shortcode... When I forked TOC+ one of the features I removed was the shortcode. The intent was to only ever support the insert TOC by the checkbox (or auto insert).

Another user submitted a pull request which added the shortcode support back in. I did not pull the code as submitted, though I used their code as a base to add shortcode support back into the plugin. Their code did not really cover the insert check box and I did not correct it. So, the shortcode really only controls the placement, overriding the global settings. A user still has to opt to insert the TOC via the checkbox. The shortcode is not enough to insert a TOC. Hoe that makes sense.

Honestly, I plan on only providing enough support for the shortcode that it work. If it is not 100% intuitive, I fine with that.

When Gutenberg is merged into WP that is what I intend on supporting for manual placement.

**Comment by shazahm1** [comment] 2018-05-04 16:55
If you have a moment.. could you please pull this and give it a quick test to make sure the notices do not show up? I merged the changes, but it broke the TOC widget so I had to tweak the eligibility check, just slightly.

**Comment by unixtam** [comment] 2018-05-04 19:33
Hi there. I do and I did, gladly. It looks like your changes defeat all of mine, since all of the code now runs whether or not a page is eligible for TOC, which is not only inefficient, but also produces the notices again.

I have merged your recent updates changes, reverted those changes that broke my fix and opened a new pull request (#37). If the widget is still broken, could you elaborate on how exactly it seems broken? I've been trying to reproduce the issue, but the widget looks fine to me.

**Comment by unixtam** [comment] 2018-05-04 20:48
I have added a Table of Contents widget to my sidebar in order to test it, and it displays as expected, including the anchor tags. Looking at the widget code in `class/class.widget-toc.php`, I see no call to either the `ezTOC::shortcode()` or the `ezTOC::the_content()` method. The widget relies directly on `ezTOC::extractHeadings()`. I don't see how my changes could possibly affect the widget. What am I missing?

The notices haven't changed from what I pasted in the first post above. They result from `$post` being empty on certain pages, which is addressed by the eligibility check.

**Comment by shazahm1** [comment] 2018-05-04 21:00
Yes, the widget will display, but the links will not work because the anchor tags in the page content will not exist. These anchor tag are added by the `the_content` method which is apply as the callback for the WP `the_content` filter. so the widget does rely on it.

To test this ... Add the widget to the sidebar. Edit the page settings for the TOC so the Insert TOC option is disabled. Make sure auto insert for the post type is also disabled.

**Comment by unixtam** [comment] 2018-05-04 22:26
Thanks, I was now able to reproduce the issue. The named anchors are missing from the content.

I assumed the eligibility check was a test for whether or not a TOC should be displayed at all, regardless of whether within the content or the widget. Perhaps the eligibility check could test whether the widget is present? It feels like there should be a more elegant solution than modifying the content regardless of whether a TOC is inserted / widget displayed or not.

For the time being, I have moved the eligibility check back again and fixed the notices by adding the ternaries in lines 599-601. See #38.

**Comment by unixtam** [comment] 2018-05-05 07:56
I've looked into it some more and I found a more elegant solution indeed by adding a check for the widget to `is_eligible()` See #39.

**Comment by unixtam** [comment] 2018-05-05 07:59
However, how the toc gets added to the post too. Give me a moment to fix this.

**Comment by shazahm1** [comment] 2018-05-06 15:16
Thanks! I'll take a look and test tomorrow. I was not aware of the `is_widget_active()` function.

**Comment by shazahm1** [comment] 2018-05-07 15:51
Ok, I tested this under the various use cases that I could think of. Everything seems fine. Merged!

**Comment by shazahm1** [comment] 2018-05-07 15:51
Even with this merged, the same errors occur in the REST requests when using Gutenberg. Probably the easy solution is to internally pass the WP_Post object instead of just the post content.

**Comment by unixtam** [comment] 2018-05-07 16:08
The bug that keeps on bugging. The issue here was that in some cases the global `$wp_query->post` was empty when `build()` was called from within `the_content()`. I currently have no Gutenberg installation to test things. Maybe things work differently in these REST requests or maybe in some cases an attempt is made to build a toc for a non-existing post? If we really have no post available, then maybe we should bail early from `the_content`. If it is available, but not via global variables, then surely, there is proper way to access it.

**Comment by shazahm1** [comment] 2018-05-07 16:57
Ok, I think this is finally squashed. Can you please pull down master and give it a quick test?

Building on your merged changes the code has been slightly refactored to pass an instance of WP_Post internally instead of trying to access it via the `$wp_query->post` global.

Here's the changeset:
https://github.com/shazahm1/Easy-Table-of-Contents/commit/fbcd546d77e4d597ca514b356cf4317d64490861

**Comment by shazahm1** [comment] 2018-05-07 17:11
ops... looks like this did introduce a regression.

**Comment by shazahm1** [comment] 2018-05-07 17:13
Nevermind, it was me paying attention! The change seems to work just fine for me in all scenarios.

**Comment by shazahm1** [comment] 2018-05-08 15:38
@unixtam 

Just wondering if you do have some time to pull the latest changes and do a quick test? If not that's ok. Let me know so I can close this.

**Comment by unixtam** [comment] 2018-05-08 17:35
Sure. The notices are fixed, the widget works and so does the shortcode. Looks good to me! :)

**Comment by shazahm1** [comment] 2018-05-09 14:17
Great to hear! I'm going to push out an update today (hopefully) or by end of week at the latest. Then I'll find out how many sites I broke :)

Closing!

**Closed by shazahm1** 2018-05-09 14:17 UTC

**Comment by unixtam** [comment] 2018-05-10 13:03
After updating, on one of my pages, I saw our favorite notices appear again. This is because on that particular page I'm calling `ezTOC::extract_headings()` directly from custom code in order to replicate the functionality of TOC+' `toc_get_index()`. You have changed the last argument from `$content` to `$post`, but my old code still feeds it the content. I updated my code, which fixed the problem, but the latest update will produce notices for anyone using custom code like I did.

Depending on how many users (or other plugins) depend on the old `extract_headings()` signature, you may or may be okay with breaking backwards compatibility. If you'd like for the changes to be backwards compatible, you could check whether $post is indeed a WP_Post object, and, if not, use the global `$wp_query->post` as you did before.

**Comment by unixtam** [comment] 2018-05-10 13:26
The same is true for `ezTOC::build()` btw.

A fix for both functions might look something like this:

```
// backwards compatibility (changed $content argument to $post)
if ( !is_object( $post ) || !($post instanceof WP_Post) ) {
	global $wp_query;
	$post = $wp_query->post;
	if ( empty( $post ) ) {
		return '';
	}
}
```

**Comment by shazahm1** [comment] 2018-05-10 13:39
I think I'm fine with the breaking change. The method was marked as private ;) even though I did leave the method itself declared public. Honestly, I might be breaking the signature again. I think I'm going to sit down and work on #13 .

Perhaps the better option would be to refactor the code for `toc_get_index()` (presently commented out) in ezTOC. I'd be open to a pull request ;) If this is something you would want to invest time in. The code for the function should be pulled out of the main class file and put in its own file and that file included in the include method of the main class file.

**Comment by shazahm1** [comment] 2018-05-10 14:28
ok, I did just push a commit which moves the commented out code to a newly included functions file.
